### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [arvindcheenu/Flutter-Calculator#1]
After I reviewed your project, your logo on this project to generikor or is this a group logo ? Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by arvindcheenu** [comment]
This is just a simple personal project that I decided to work and expand on to create a single unified project that explores most commonly used Flutter Components. Thus, all the basics of flutter could be explored in a single example. 

Thanks, I will be glad to receive your contributions. 
It would be of a great help, not only for me but for the Flutter Community as a whole.

**Comment by mansya** [comment]
Hi sir, I have design logo for this project. what do you think ? do you like it ? wich one do you like it ?

![flutter calculator](https://user-images.githubusercontent.com/33461607/43670608-cccdc476-97b7-11e8-9ffe-453c1365cb15.png)

sorry for a long time sir. thanks

**Comment by arvindcheenu** [comment]
I like the 7th. It complements with the design.

**Comment by mansya** [comment]
I have upload all files to this link.
https://drive.google.com/open?id=1U7PPJnxbQJsWm1GI2C0XkyAdk8FKOTw3

And I have sent you pull requests. please check it.

**Comment by arvindcheenu** [comment]
All done. Thanks again for the contribution.
